
server:
  port: 8082

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?createDatabaseIfNotExist=true
    username: root
    password: chandu@teja
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect

logging:
  level:
    com.com.storesmanagementsystem.product.client.config.UserServiceClient: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000